# Generated by Django 5.0.1 on 2024-01-26 23:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sitevs", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="sitevs",
            new_name="sitev",
        ),
    ]
