# Generated by Django 5.0.1 on 2024-01-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sitevs", "0002_rename_sitevs_sitev"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitev",
            name="deadline",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="sitev",
            name="finished_at",
            field=models.DateField(null=True),
        ),
    ]
